src/EditorialBundle/Entity/Article.php
<?php

namespace EditorialBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use EditorialBundle\Enum\ArticleStatus;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Article
 *
 * @ORM\Table(name="articles")
 * @ORM\Entity(repositoryClass="EditorialBundle\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     * @Assert\NotBlank(message="Zadejte název článku")
     * @Assert\Length(max="255", maxMessage="Maximální délka názvu je {{ limit }} znaků")
     */
    private $name;

    /**
     * @var int
     *
     * @ORM\Column(name="status", type="integer")
     */
    private $status;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created", type="datetime")
     */
    private $created;

    /**
     * @var ArrayCollection|ArticleVersion[]
     *
     * @ORM\OneToMany(targetEntity="ArticleVersion", mappedBy="article", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $versions;

    /**
     * @var ArrayCollection|ArticleAuthor[]
     *
     * @ORM\OneToMany(targetEntity="ArticleAuthor", mappedBy="article", cascade={"persist", "remove"}, orphanRemoval=true)
     * @Assert\Valid()
     * @Assert\Count(min="1", minMessage="Článek musí mít alespoň jednoho autora")
     */
    private $authors;

    /**
     * @var Magazine
     *
     * @ORM\ManyToOne(targetEntity="Magazine", inversedBy="articles")
     * @ORM\JoinColumn(name="magazine_id", referencedColumnName="id")
     */
    private $magazine;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="User", inversedBy="authorArticles")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $owner;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="User", inversedBy="editorArticles")
     * @ORM\JoinColumn(name="editor_id", referencedColumnName="id", nullable=true)
     */
    private $editor;

    /**
     * @var ArrayCollection|Review[]
     *
     * @ORM\OneToMany(targetEntity="Review", mappedBy="article", cascade={"persist"})
     */
    private $reviews;

    /**
     * @var ArrayCollection|ArticleComment[]
     *
     * @ORM\OneToMany(targetEntity="ArticleComment", mappedBy="article", cascade={"persist"})
     */
    private $comments;

    public function __construct()
    {
        $this->versions = new ArrayCollection();
        $this->authors = new ArrayCollection();
        $this->reviews = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->created = new \DateTime();
        $this->status = ArticleStatus::STATUS_NEW;
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name.
     *
     * @param string $name
     *
     * @return Article
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set status.
     *
     * @param int $status
     *
     * @return Article
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status.
     *
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * @param ArticleVersion $version
     * @return Article
     */
    public function addVersion(ArticleVersion $version)
    {
        if (!$this->versions->contains($version)) {
            $this->versions[] = $version;
            $version->setArticle($this);
        }

        return $this;
    }

    /**
     * @param ArticleVersion $version
     * @return Article
     */
    public function removeVersion(ArticleVersion $version)
    {
        if ($this->versions->contains($version)) {
            $this->versions->removeElement($version);

            if ($version->getArticle() === $this) {
                $version->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return ArrayCollection|ArticleVersion[]
     */
    public function getVersions()
    {
        return $this->versions;
    }

    /**
     * @param ArticleAuthor $author
     * @return Article
     */
    public function addAuthor(ArticleAuthor $author)
    {
        if (!$this->authors->contains($author)) {
            $this->authors[] = $author;
            $author->setArticle($this);
        }

        return $this;
    }

    /**
     * @param ArticleAuthor $author
     * @return Article
     */
    public function removeAuthor(ArticleAuthor $author)
    {
        if ($this->authors->contains($author)) {
            $this->authors->removeElement($author);

            if ($author->getArticle() === $this) {
                $author->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return ArrayCollection|ArticleAuthor[]
     */
    public function getAuthors()
    {
        return $this->authors;
    }

    /**
     * @param Magazine $magazine
     * @return Article
     */
    public function setMagazine(Magazine $magazine = null)
    {
        $this->magazine = $magazine;

        return $this;
    }

    /**
     * @return Magazine
     */
    public function getMagazine()
    {
        return $this->magazine;
    }

    /**
     * @param User $owner
     * @return Article
     */
    public function setOwner(User $owner = null)
    {
        $this->owner = $owner;

        return $this;
    }

    /**
     * @return User
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * @param User $editor
     * @return Article
     */
    public function setEditor(User $editor = null)
    {
        $this->editor = $editor;

        return $this;
    }

    /**
     * @return User
     */
    public function getEditor()
    {
        return $this->editor;
    }

    /**
     * @param Review $review
     * @return Article
     */
    public function addReview(Review $review)
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setArticle($this);
        }

        return $this;
    }

    /**
     * @param Review $review
     * @return Article
     */
    public function removeReview(Review $review)
    {
        if ($this->reviews->contains($review)) {
            $this->reviews->removeElement($review);

            if ($review->getArticle() === $this) {
                $review->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return ArrayCollection|Review[]
     */
    public function getReviews()
    {
        return $this->reviews;
    }

    /**
     * @param ArticleComment $comment
     * @return Article
     */
    public function addComment(ArticleComment $comment)
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    /**
     * @param ArticleComment $comment
     * @return Article
     */
    public function removeComment(ArticleComment $comment)
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);

            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return ArrayCollection|ArticleComment[]
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * @return string
     */
    public function getMagazineChoiceName()
    {
        if ($this->magazine) {
            return $this->magazine->getChoiceName();
        }

        return '';
    }

    /**
     * @return ArticleVersion|null
     */
    public function getLastVersion()
    {
        return $this->versions->isEmpty() ? null : $this->versions->last();
    }

    /**
     * @return string
     */
    public function getOwnerInfo()
    {
        if ($owner = $this->getOwner()) {
            return $owner->getDisplayName();
        }

        return '';
    }

    /**
     * @return string
     */
    public function getEditorInfo()
    {
        if ($editor = $this->getEditor()) {
            return $editor->getDisplayName();
        }

        return '';
    }

    /**
     * @return string
     */
    public function getEditorEmail()
    {
        if ($editor = $this->getEditor()) {
            return $editor->getEmail();
        }

        return '';
    }

    /**
     * @return string
     */
    public function getOwnerEmail()
    {
        if ($owner = $this->getOwner()) {
            return $owner->getEmail();
        }

        return '';
    }

    /**
     * @return int|string
     */
    public function getMagazineYear()
    {
        if ($magazine = $this->getMagazine()) {
            return $magazine->getYear();
        }

        return '';
    }

    /**
     * @return int|string
     */
    public function getMagazineNumber()
    {
        if ($magazine = $this->getMagazine()) {
            return $magazine->getNumber();
        }

        return '';
    }

    /**
     * @return bool
     */
    public function hasAllReviewsFilled()
    {
        foreach ($this->getReviews() as $review) {
            if (!$review->isFilled()) {
                return false;
            }
        }

        return true;
    }
}

src/EditorialBundle/Form/ArticleType.php
<?php

namespace EditorialBundle\Form;

use Doctrine\ORM\EntityRepository;
use EditorialBundle\Entity\Article;
use EditorialBundle\Entity\Magazine;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\NotBlank;

class ArticleType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Název článku',
            ])
            ->add('magazine', EntityType::class, [
                'class' => Magazine::class,
                'label' => 'Číslo časopisu',
                'choice_label' => 'choiceName',
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('m')
                        ->where('m.deadlineDate > :now')
                        ->setParameter('now', new \DateTime())
                    ;
                }
            ])
            ->add('file', FileType::class, [
                'label' => 'Článek',
                'mapped' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '20M',
                        'maxSizeMessage' => 'Maximální velikost je 20MB',
                        'mimeTypes' => [
                            'application/msword',
                            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                        ]
                    ]),
                    new NotBlank(['message' => 'Vyberte soubor se článkem']),
                ],
            ])
            ->add('authors', CollectionType::class, [
                'label' => false,
                'entry_type' => ArticleAuthorType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
                'error_bubbling' => true,
            ])
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'editorialbundle_article';
    }
}

src/EditorialBundle/Controller/ArticleController.php
<?php

namespace EditorialBundle\Controller;

use EditorialBundle\Entity\Article;
use EditorialBundle\Entity\ArticleComment;
use EditorialBundle\Entity\User;
use EditorialBundle\Form\ArticleCommentType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/redakce/clanek")
 */
class ArticleController extends Controller
{
    /**
     * @Route("/{id}/detail", name="article_detail", methods={"GET"})
     * @Security("is_granted('DETAIL', article)", message="Nemáte oprávnění na náhled článku")
     */
    public function detailAction(Article $article)
    {
        return $this->render('@Editorial/Article/detail.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * @Route("/{id}/pridat-komentar", name="article_comment_add", methods={"GET", "POST"})
     * @Security("is_granted('COMMENT', article)", message="Nemáte oprávnění pro přidávání komentářů")
     */
    public function addCommentAction(Request $request, Article $article)
    {
        /** @var User $user */
        $user = $this->getUser();
        $form = $this->createForm(ArticleCommentType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var ArticleComment $comment */
            $comment = $form->getData();
            $comment->setUser($user);
            $comment->setArticle($article);

            $em = $this->getDoctrine()->getManager();
            $em->persist($comment);
            $em->flush();

            return $this->redirectToRoute('article_detail', ['id' => $article->getId(), '_fragment' => 'diskuse']);
        }

        return $this->render('@Editorial/Article/addComment.html.twig', [
            'form' => $form->createView(),
            'article' => $article,
        ]);
    }
}

src/EditorialBundle/Resources/views/Editor/Article/assignReviewers.html.twig
{% extends '@Editorial/base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block title %}Výběr recenzentů{% endblock %}

{% block content %}
    <h1>{{ block('title') }}</h1>
    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-primary">Vybrat</button>
    {{ form_end(form) }}
{% endblock %}

src/EditorialBundle/Resources/views/Editor/Article/assignedToEditorList.html.twig
{% extends '@Editorial/base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{% import '@Editorial/Macros/tableHead.html.twig' as th %}

{% block title %}Články přiřazené mně{% endblock %}

{% block content %}
    <h1>{{ block('title') }}</h1>

    {{ form_start(form) }}
        <div class="row">
            <div class="col-sm">{{ form_row(form.name) }}</div>
            <div class="col-sm">{{ form_row(form.status) }}</div>
        </div>
        <div class="row">
            <div class="col-sm">{{ form_row(form.magazine) }}</div>
            <div class="col-sm">{{ form_row(form.author) }}</div>
        </div>
        <button class="btn btn-primary">Filtrovat</button>
    {{ form_end(form) }}

    <table class="table table-striped mt-5">
        <thead>
            <tr>
                {{ th.nav(pagination, 'a.id', '#') }}
                {{ th.nav(pagination, 'a.name', 'Název článku') }}
                {{ th.nav(pagination, 'o.username', 'Vlastník') }}
                {{ th.nav(pagination, 'm.id', 'Číslo časopisu') }}
                {{ th.nav(pagination, 'a.status', 'Status') }}
                <th scope="col">Akce</th>
            </tr>
        </thead>
        <tbody>
        {% for article in pagination %}
            <tr>
                <th scope="row">{{ article.id }}</th>
                <td>{{ article.name }}</td>
                <td>{{ article.ownerInfo }}</td>
                <td>{{ article.magazineChoiceName }}</td>
                <td class="status-{{ article|statusClass }}">{{ article|statusName }}</td>
                <td>
                    <a href="{{ path('article_detail', {id: article.id}) }}" class="btn btn-sm btn-success mb-1">Detail</a>
                    <a href="{{ path('download_article', {id: article.id}) }}" class="btn btn-sm btn-primary mb-1">Stáhnout</a>
                    {% if is_granted('ADD_REVIEWER', article) %}
                        <a href="{{ path('editor_article_add_reviewers', {id: article.id}) }}" class="btn btn-sm btn-info mb-1">
                            {% if article.status is constant('EditorialBundle\\Enum\\ArticleStatus::STATUS_ASSIGNED') %}Vybrat recenzenty{% else %}Přidat recenzenty{% endif %}
                        </a>
                    {% endif %}
                    {% if is_granted('CHANGE_STATUS', article) %}
                        <a href="{{ path('editor_article_change_status', {id: article.id}) }}" class="btn btn-sm btn-warning mb-1">Upravit status</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="pagination-navigation">
        {{ knp_pagination_render(pagination) }}
    </div>
    <div class="pagination-count">
        Celkem: {{ pagination.totalItemCount }}
    </div>
{% endblock %}

src/EditorialBundle/Resources/views/Editor/Article/changeStatus.html.twig
{% extends '@Editorial/base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block title %}Upravit status{% endblock %}

{% block content %}
    <h1>Upravit status</h1>
    <ul class="list-group list-group-flush mb-5">
        <li class="list-group-item"><b>Článek:</b> {{ article.name }}</li>
        <li class="list-group-item"><b>Aktuální status:</b> <span class="status-{{ article|statusClass }}">{{ article|statusName }}</span></li>
    </ul>
    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-primary">Upravit</button>
    {{ form_end(form) }}
{% endblock %}

src/EditorialBundle/Resources/views/Editor/Article/unassignedList.html.twig
{% extends '@Editorial/base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{% import '@Editorial/Macros/tableHead.html.twig' as th %}

{% block title %}Nepřiřazené články{% endblock %}

{% block content %}
    <h1>{{ block('title') }}</h1>

    {{ form_start(form) }}
        <div class="row">
            <div class="col-sm">{{ form_row(form.name) }}</div>
            <div class="col-sm">{{ form_row(form.status) }}</div>
        </div>
        <div class="row">
            <div class="col-sm">{{ form_row(form.magazine) }}</div>
            <div class="col-sm">{{ form_row(form.author) }}</div>
        </div>
        <button class="btn btn-primary">Filtrovat</button>
    {{ form_end(form) }}

    <table class="table table-striped mt-5">
        <thead>
            <tr>
                {{ th.nav(pagination, 'a.id', '#') }}
                {{ th.nav(pagination, 'a.name', 'Název článku') }}
                {{ th.nav(pagination, 'o.username', 'Vlastník') }}
                {{ th.nav(pagination, 'm.id', 'Číslo časopisu') }}
                {{ th.nav(pagination, 'a.status', 'Status') }}
                <th scope="col">Akce</th>
            </tr>
        </thead>
        <tbody>
            {% for article in pagination %}
                <tr>
                    <th scope="row">{{ article.id }}</th>
                    <td>{{ article.name }}</td>
                    <td>{{ article.ownerInfo }}</td>
                    <td>{{ article.magazineChoiceName }}</td>
                    <td class="status-{{ article|statusClass }}">{{ article|statusName }}</td>
                    <td>
                        <a href="{{ path('article_detail', {id: article.id}) }}" class="btn btn-sm btn-info mb-1">Detail</a>
                        <a href="{{ path('download_article', {id: article.id}) }}" class="btn btn-sm btn-primary mb-1">Stáhnout</a>
                        <form class="d-inline" action="{{ path('editor_article_assign', {id: article.id}) }}" method="post">
                            <input type="hidden" name="_token" value="{{ csrf_token('assign_article') }}">
                            <button class="btn btn-sm btn-success mb-1">Začít recenzní řízení</button>
                        </form>
                        {% if is_granted('CHANGE_STATUS', article) %}
                            <a href="{{ path('editor_article_change_status', {id: article.id}) }}" class="btn btn-sm btn-warning mb-1">Upravit status</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="pagination-navigation">
        {{ knp_pagination_render(pagination) }}
    </div>
    <div class="pagination-count">
        Celkem: {{ pagination.totalItemCount }}
    </div>
{% endblock %}