src/EditorialBundle/Entity/HelpDeskMessage.php
<?php

namespace EditorialBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * HelpDeskMessage
 *
 * @ORM\Table(name="helpdesk_messages")
 * @ORM\Entity(repositoryClass="EditorialBundle\Repository\HelpDeskMessageRepository")
 */
class HelpDeskMessage
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="message", type="text")
     * @Assert\NotBlank(message="Zadejte prosím zprávu")
     */
    private $message;

    /**
     * @var string|null
     *
     * @ORM\Column(name="answer", type="text", nullable=true)
     * @Assert\NotBlank(message="Zadejte odpověď", groups={"Answer"})
     */
    private $answer;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created", type="datetime")
     */
    private $created;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="answered", type="datetime", nullable=true)
     */
    private $answered;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=100)
     * @Assert\NotBlank(message="Zadejte prosím e-mail")
     * @Assert\Email(message="E-mail není ve správném tvaru")
     */
    private $email;

    /**
     * @var User|null
     *
     * @ORM\ManyToOne(targetEntity="User", inversedBy="helpDeskMessages")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=true)
     */
    private $manager;

    public function __construct()
    {
        $this->created = new \DateTime();
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set message.
     *
     * @param string $message
     *
     * @return HelpDeskMessage
     */
    public function setMessage($message)
    {
        $this->message = $message;

        return $this;
    }

    /**
     * Get message.
     *
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Set answer.
     *
     * @param string|null $answer
     *
     * @return HelpDeskMessage
     */
    public function setAnswer($answer = null)
    {
        $this->answer = $answer;

        return $this;
    }

    /**
     * Get answer.
     *
     * @return string|null
     */
    public function getAnswer()
    {
        return $this->answer;
    }

    /**
     * Set created.
     *
     * @param \DateTime $created
     *
     * @return HelpDeskMessage
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created.
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set answered.
     *
     * @param \DateTime|null $answered
     *
     * @return HelpDeskMessage
     */
    public function setAnswered($answered = null)
    {
        $this->answered = $answered;

        return $this;
    }

    /**
     * Get answered.
     *
     * @return \DateTime|null
     */
    public function getAnswered()
    {
        return $this->answered;
    }

    /**
     * Set email.
     *
     * @param string $email
     *
     * @return HelpDeskMessage
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email.
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set Manager
     *
     * @param User|null $manager
     * @return HelpDeskMessage
     */
    public function setManager(User $manager = null)
    {
        $this->manager = $manager;

        return $this;
    }

    /**
     * Get Manager
     *
     * @return User|null
     */
    public function getManager()
    {
        return $this->manager;
    }

    public function getManagerInfo()
    {
        if ($manager = $this->getManager()) {
            return $manager->getDisplayName();
        }

        return '';
    }
}

src/EditorialBundle/Controller/HelpDeskController.php
<?php


namespace EditorialBundle\Controller;

use EditorialBundle\Entity\HelpDeskMessage;
use EditorialBundle\Entity\User;
use EditorialBundle\Factory\EmailFactory;
use EditorialBundle\Form\HelpDeskAnswerType;
use EditorialBundle\Repository\HelpDeskMessageRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/redakce/helpdesk")
 * @Security("has_role('ROLE_HELP_DESK')")
 */
class HelpDeskController extends Controller
{
    /**
     * @Route("/nezodpovezene", name="help_desk_unanswered", methods={"GET"})
     */
    public function unansweredAction()
    {
        /** @var HelpDeskMessageRepository $repository */
        $repository = $this->getDoctrine()->getRepository(HelpDeskMessage::class);
        /** @var HelpDeskMessage[] $messages */
        $messages = $repository->findUnanswered();

        return $this->render('@Editorial/HelpDesk/unansweredList.html.twig', [
            'messages' => $messages,
        ]);
    }

    /**
     * @Route("/zodpovezene", name="help_desk_answered", methods={"GET"})
     */
    public function answeredAction()
    {
        /** @var HelpDeskMessageRepository $repository */
        $repository = $this->getDoctrine()->getRepository(HelpDeskMessage::class);
        /** @var HelpDeskMessage[] $messages */
        $messages = $repository->findAnswered();

        return $this->render('@Editorial/HelpDesk/answeredList.html.twig', [
            'messages' => $messages,
        ]);
    }

    /**
     * @Route("/odpovedet/{id}", name="help_desk_add_answer", methods={"GET", "POST"})
     * @Security("is_granted('ANSWER', message)", message="Zpráva již byla zodpovězena nebo ignorována")
     */
    public function addAnswerAction(Request $request, HelpDeskMessage $message, EmailFactory $emailFactory)
    {
        /** @var User $user */
        $user = $this->getUser();
        $form = $this->createForm(HelpDeskAnswerType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var HelpDeskMessage $message */
            $message = $form->getData();
            $message->setAnswered(new \DateTime());
            $message->setManager($user);

            $em = $this->getDoctrine()->getManager();
            $em->flush();

            $emailFactory->sendHelpDeskAnswer($message);
            $this->addFlash('success', 'Email s odpovědí byl odeslán');

            return $this->redirectToRoute('help_desk_answered');
        }

        return $this->render('@Editorial/HelpDesk/addAnswer.html.twig', [
            'form' => $form->createView(),
            'message' => $message,
        ]);
    }

    /**
     * @Route("/ingorovat/{id}", name="help_desk_ignore", methods={"POST"})
     * @Security("is_granted('IGNORE', message)", message="Zpráva již byla zodpovězena nebo ignorována")
     */
    public function ignoreAction(Request $request, HelpDeskMessage $message)
    {
        if (!$this->isCsrfTokenValid('help_desk_ignore', $request->get('_token'))) {
            $this->addFlash('danger', 'Neplatný CSRF token. Zkuste to prosím znovu');

            return $this->redirectToRoute('help_desk_unanswered');
        }

        /** @var User $user */
        $user = $this->getUser();
        $message->setManager($user);

        $em = $this->getDoctrine()->getManager();
        $em->flush();

        $this->addFlash('success', 'Zpráva byla zařazena mezi ignorované');

        return $this->redirectToRoute('help_desk_unanswered');
    }

    /**
     * @Route("/detail/{id}", name="help_desk_detail", methods={"GET", "POST"})
     */
    public function detailAction(HelpDeskMessage $message)
    {
        return $this->render('@Editorial/HelpDesk/detail.html.twig', [
            'message' => $message,
        ]);
    }
}

src/EditorialBundle/Resources/views/HelpDesk/addAnswer.html.twig
{% extends '@Editorial/base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block title %}Přidat odpověď na helpdesk zprávu{% endblock %}

{% block content %}
    <h1>{{ block('title') }}</h1>
    <p>{{ message.message }}</p>
    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-primary">Odeslat</button>
    {{ form_end(form) }}
{% endblock %}

src/EditorialBundle/Resources/views/HelpDesk/answeredList.html.twig
{% extends '@Editorial/base.html.twig' %}

{% block title %}Zodpovězené helpdesk zprávy{% endblock %}

{% block content %}
    <h1>{{ block('title') }}</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">E-mail</th>
                <th scope="col">Vytvořeno</th>
                <th scope="col">Náhled</th>
                <th scope="col">Odpověděl</th>
                <th scope="col">Akce</th>
            </tr>
        </thead>
        <tbody>
            {% for message in messages %}
                <tr>
                    <th scope="row">{{ message.id }}</th>
                    <td>{{ message.email }}</td>
                    <td>{{ message.created|date('d. m. Y H:i') }}</td>
                    <td>{{ message.message|slice(0, 50) }}...</td>
                    <td>{{ message.managerInfo }}</td>
                    <td>
                        <a href="{{ path('help_desk_detail', {id: message.id}) }}" class="btn btn-sm btn-primary mb-1">Detail</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/EditorialBundle/Resources/views/HelpDesk/detail.html.twig
{% extends '@Editorial/base.html.twig' %}

{% block title %}Detail zprávy z helpdesku{% endblock %}

{% block content %}
    <h1>{{ block('title') }}</h1>
    <h4>Zpráva</h4>
    <p>{{ message.message }}</p>
    <h4>Odpověď</h4>
    <p>{{ message.answer }}</p>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><b>Vytvořeno:</b> {{ message.created|date('d. m. Y') }}</li>
        <li class="list-group-item"><b>Zodpovězeno:</b> {{ message.answered|date('d. m. Y') }}</li>
        <li class="list-group-item"><b>Zodpověděl:</b> {{ message.managerInfo }}</li>
    </ul>
{% endblock %}

src/EditorialBundle/Resources/views/HelpDesk/unansweredList.html.twig
{% extends '@Editorial/base.html.twig' %}

{% block title %}Nezodpovězené helpdesk zprávy{% endblock %}

{% block content %}
    <h1>{{ block('title') }}</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">E-mail</th>
                <th scope="col">Vytvořeno</th>
                <th scope="col">Náhled</th>
                <th scope="col">Akce</th>
            </tr>
        </thead>
        <tbody>
            {% for message in messages %}
                <tr>
                    <th scope="row">{{ message.id }}</th>
                    <td>{{ message.email }}</td>
                    <td>{{ message.created|date('d. m. Y H:i') }}</td>
                    <td>{{ message.message|slice(0, 50) }}...</td>
                    <td>
                        <a href="{{ path('help_desk_add_answer', {id: message.id}) }}" class="btn btn-sm btn-success mb-1">Odpovědět</a>
                        <form class="d-inline" action="{{ path('help_desk_ignore', {id: message.id}) }}" method="post" onsubmit="return confirm('Jste si jistý')">
                            <input type="hidden" name="_token" value="{{ csrf_token('help_desk_ignore') }}">
                            <button class="btn btn-sm btn-danger mb-1">Ignorovat</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}